FROM node:22-alpine

WORKDIR /usr/src/app

RUN corepack enable

COPY ./packages ./packages

COPY ./package.json ./package.json

COPY ./turbo.json ./turbo.json

COPY ./apps/fe ./apps/fe

RUN pnpm install

COPY . .

RUN pnpm run db:migrate

EXPOSE 3000

CMD ["npm" , "run" ,"buildfe"]