FROM node:22-alpine
WORKDIR /usr/src/app
RUN corepack enable

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN pnpm run db:migrate

EXPOSE 3002

CMD ["pnpm", "run", "buildbackend"]